version: '3.1'
services:
  mysql4oauth:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql4oauthv:/var/lib/mysql
volumes:
  mysql4oauthv: